  variables:
  buildConfiguration: 'Release'

steps:
  - task: CopyFiles@2
    displayName: 'Copy HTML files'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)'
      Contents: '**/*.html'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/html-artifact'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/html-artifact'
      ArtifactName: 'html-artifact'
      publishLocation: 'Container'

  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Devops_Demo_ServiceConnection'
      appType: 'webAppLinux'
      appName: 'DevopsDemoWeb'
      package: '$(System.DefaultWorkingDirectory)/html-artifact/**/*.html'

