variables:
  buildConfiguration: 'Release'

steps:
# No dotnet build is needed for an HTML site

- task: CopyFiles@2
  displayName: 'Copy HTML files'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: '**/*.html'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'html-artifact'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Towards-AzurePortal'
    appType: 'webAppLinux'
    appName: 'DevopsDemoWeb'
    package: '$(Build.ArtifactStagingDirectory)/html-artifact/**/*.html'
